# config
cover: /img/img-bg.jpg
logo: /img/avatar.jpg
bio: 五道口男子理工技术学院，黑科技爱好者

# Content
excerpt_link: READ MORE

# Header  nav
menu:
  Home: /
  Archive: /archive
  Images: /images
  Wiki: /wiki
  Favorites: /favorites
  Contact: /about

##Private: /private

# nav.fonticon.css
navclass:
  Home: icon-home
  Archive: icon-news
  Images: icon-image
  Wiki: icon-wiki
  Favorites: icon-Favorites
  Contact: icon-mail

##Private: icon-lock
rss: /atom.xml

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
fancybox: true
